CREATE TABLE IF NOT EXISTS users (
  tg_user_id BIGINT PRIMARY KEY,
  tg_username VARCHAR(64) NULL,
  nickname VARCHAR(16) NOT NULL,
  status ENUM('pending','approved','rejected') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tg_user_id BIGINT NOT NULL,
  tg_username VARCHAR(64) NULL,
  nickname VARCHAR(16) NOT NULL,
  status ENUM('pending','approved','rejected') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (status),
  INDEX (tg_user_id)
);

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actor_tg_id BIGINT NULL,
  action VARCHAR(32) NOT NULL,
  nickname VARCHAR(16) NULL,
  request_id BIGINT NULL,
  result VARCHAR(16) NOT NULL,
  error_text TEXT NULL
);

CREATE TABLE IF NOT EXISTS admins (
  tg_user_id BIGINT PRIMARY KEY,
  role VARCHAR(16) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
